spring.application.name=be
# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:cmsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cho phép Hibernate t? t?o b?ng t? Entity
spring.jpa.hibernate.ddl-auto=update

# B?t H2 Console ?? qu?n lý DB qua trình duy?t (localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true